services:
  linebot-gpt-db:
    image: postgres:17.6
    container_name: linebot-gpt-db
    env_file:
      - .env
    ports:
      - "65432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  linebot-gpt:
    build: .
    container_name: linebot-gpt
    env_file:
      - .env
    depends_on:
        - linebot-gpt-db
    ports:
      - "18000:8000"
    tty: true
    restart: unless-stopped

